      BLOCK DATA BCONST
C:
C: BCONST 91-02-04  MODIFICATIONS: (MATS CARLSSON)
C:        DATA STATEMENT OF NEWSTA AND IRC MOVED FROM OPEN ROUTINE
C:        TO BCONST AND TRANSFERED IN CBCNST
C:
C:        07-12-30  MODIFICATIONS: (MATS CARLSSON)
C:        IRC NOW SET AUTOMATICALLY IN MOPEN
C:
      INCLUDE 'PREC'
      INCLUDE 'PARAM'
      INCLUDE 'CTRAN'
      INCLUDE 'CSLINE'
      INCLUDE 'CCONST'
      INCLUDE 'CBCNST'
      INCLUDE 'C3D'
C
      DATA TAUQ(0)/0./,X(0)/0.0/
      DATA EE/1.602189E-12/,HH/6.626176E-27/,CC/2.99792458E10/,
     * EM/9.109534E-28/,UU/1.6605655E-24/,BK/1.380662E-16/,
     * PI/3.14159265359/
      DATA L3D/.FALSE./
C
C  MACHINE DEPENDENT DATA:
C  NEWSTA   ACTUAL STATUS USED IN OPEN WHEN ASKED FOR STATUS='NEW'
C           RECOMMENDED VALUES:
C           VMS    'NEW'     GIVES A NEW VERSION
C           UNIX   'UNKNOWN' PREVENTS CRASH IF FILE ALREADY EXISTS
C
      DATA NEWSTA/'UNKNOWN'/
C
      END
C
C***********************************************************************
C
